# Generated by Django 4.2.17 on 2026-03-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileuploads', '0008_documentembedding_metadata_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geospatial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('buffer', 'Buffer'), ('interseccion', 'Intersección'), ('densidad', 'Densidad'), ('avanzado', 'Avanzado')], max_length=50)),
                ('export_format', models.CharField(default='geojson', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Listo'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('geonode_url', models.URLField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geospatial_spatializations', to='fileuploads.context')),
                ('files_used', models.ManyToManyField(blank=True, related_name='geospatial_files', to='fileuploads.files')),
            ],
            options={
                'indexes': [models.Index(fields=['context'], name='geospatial__context_ae922c_idx'), models.Index(fields=['status'], name='geospatial__status_340832_idx'), models.Index(fields=['user_id'], name='geospatial__user_id_39fbe5_idx')],
            },
        ),
    ]
