# Generated by Django 4.2.17 on 2025-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('chat', models.JSONField(blank=True, null=True)),
                ('history_array', models.JSONField(blank=True, null=True)),
                ('credate_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('job_status', models.TextField(blank=True, null=True)),
                ('context', models.ManyToManyField(blank=True, to='fileuploads.context')),
            ],
        ),
    ]
