# Generated by Django 4.2.17 on 2025-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
