# Generated by Django 4.2.17 on 2025-09-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_history_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
