# Generated by Django 4.2.17 on 2026-02-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_context_797e89_idx',
            old_name='reports_rep_context_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_report__dbb097_idx',
            old_name='reports_rep_report_type_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_status_c732ef_idx',
            old_name='reports_rep_status_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_user_id_f032ac_idx',
            old_name='reports_rep_user_id_idx',
        ),
    ]
