# Generated by Django 4.2.17 on 2026-02-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reports_rep_context_idx_reports_rep_context_797e89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='geonode_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='geonode_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word (.docx)'), ('csv', 'CSV'), ('pptx', 'PowerPoint (.pptx)')], default='pdf', max_length=20),
        ),
    ]
