# Generated by Django 4.2.17 on 2026-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_geonode_id_report_geonode_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word (.docx)'), ('csv', 'CSV'), ('pptx', 'PowerPoint (.pptx)'), ('txt', 'Texto plano (.txt)')], default='pdf', max_length=20),
        ),
    ]
