# Generated by Django 4.2.17 on 2026-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('institutional', 'Institucional'), ('descriptive', 'Descriptivo'), ('summary', 'Resumen'), ('evaluation', 'Evaluación'), ('presentation', 'Presentación')], max_length=50),
        ),
    ]
