# Generated by Django 4.2.17 on 2026-03-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileuploads', '0008_documentembedding_metadata_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spatialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('entity_types', models.JSONField(blank=True, null=True)),
                ('export_format', models.CharField(default='geojson', max_length=20)),
                ('geometry_type', models.CharField(default='point', max_length=20)),
                ('focus', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Listo'), ('error', 'Error')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('geonode_url', models.URLField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatializations', to='fileuploads.context')),
                ('files_used', models.ManyToManyField(blank=True, related_name='spatializations', to='fileuploads.files')),
            ],
            options={
                'indexes': [models.Index(fields=['context'], name='localidades_context_1b0c02_idx'), models.Index(fields=['status'], name='localidades_status_f7dcc6_idx'), models.Index(fields=['user_id'], name='localidades_user_id_8ba3ef_idx')],
            },
        ),
    ]
