# Generated by Django 4.2.17 on 2026-03-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialization',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
