# Generated by Django 4.2.17 on 2025-07-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('type_image', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('type_image', models.TextField(default='')),
                ('technical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.workspace')),
            ],
        ),
    ]
