# Generated by Django 4.2.17 on 2025-07-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexado_id', models.UUIDField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('type_document', models.TextField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='context',
            name='technical',
        ),
        migrations.AddField(
            model_name='context',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.workspace'),
        ),
        migrations.CreateModel(
            name='Indexado_Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.context')),
                ('indexado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.indexado')),
            ],
        ),
    ]
