# Generated by Django 4.2.17 on 2025-08-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='files',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='files',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.workspace'),
        ),
    ]
