# Generated by Django 4.2.17 on 2025-08-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='files',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
