# Generated by Django 4.2.17 on 2025-08-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='contexts', to='fileuploads.files'),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='language',
            field=models.CharField(default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='files',
            name='language',
            field=models.CharField(default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='files',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.workspace'),
        ),
        migrations.AlterField(
            model_name='context',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contextos', to='fileuploads.workspace'),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='fileuploads.files'),
        ),
        migrations.AddIndex(
            model_name='context',
            index=models.Index(fields=['workspace'], name='fileuploads_workspa_8eb442_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['file'], name='fileuploads_file_id_37dc55_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['language'], name='fileuploads_languag_81bad9_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['workspace'], name='fileuploads_workspa_b26adf_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['language'], name='fileuploads_languag_ed16a0_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['user_id'], name='fileuploads_user_id_85b3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['public'], name='fileuploads_public_22f89a_idx'),
        ),
    ]
