# Generated by Django 4.2.17 on 2025-07-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_indexado_remove_context_technical_context_workspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='type_image',
        ),
        migrations.AddField(
            model_name='workspace',
            name='image_uuid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
