# Generated by Django 4.2.17 on 2025-08-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_context_files_documentembedding_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='geonode_type',
            field=models.TextField(default=''),
        ),
    ]
