# Generated by Django 4.2.17 on 2025-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0003_files_geonode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='user_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
