# Generated by Django 4.2.17 on 2025-08-01 16:57

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0003_remove_workspace_type_image_workspace_image_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('document_type', models.TextField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indexado_context',
            name='context',
        ),
        migrations.RemoveField(
            model_name='indexado_context',
            name='indexado',
        ),
        migrations.RemoveField(
            model_name='context',
            name='type_image',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='image_uuid',
        ),
        migrations.AddField(
            model_name='context',
            name='image_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='image_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Indexado',
        ),
        migrations.DeleteModel(
            name='Indexado_Context',
        ),
        migrations.AddField(
            model_name='files',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploads.context'),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='fileuploads.files'),
        ),
    ]
