# Generated by Django 4.2.17 on 2025-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0004_alter_context_user_id_alter_files_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='document_id',
        ),
        migrations.AddField(
            model_name='files',
            name='geonode_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='geonode_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
