# Generated by Django 4.2.17 on 2025-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0005_remove_files_document_id_files_geonode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='geonode_category',
            field=models.TextField(default=''),
        ),
    ]
