# Generated by Django 4.2.17 on 2025-11-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0006_files_geonode_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='text_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
