# Generated by Django 4.2.17 on 2025-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0007_documentembedding_text_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
