# Generated by Django 5.2.4 on 2026-01-22 18:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0008_documentembedding_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='fileuploads_search__c47671_gin'),
        ),
    ]
