# Generated by Django 4.2.17 on 2026-01-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0009_documentembedding_search_vector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentembedding',
            new_name='fileuploads_search__668718_gin',
            old_name='fileuploads_search__c47671_gin',
        ),
    ]
